# Generated by Django 4.2.6 on 2023-12-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YogaParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('selected_batch', models.CharField(choices=[('6-7AM', '6-7AM'), ('7-8AM', '7-8AM'), ('8-9AM', '8-9AM'), ('5-6PM', '5-6PM')], max_length=10)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
